# Generated by Django 2.2.1 on 2019-05-06 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default.png', max_length=50, upload_to='profile')),
                ('last_modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(blank=True, max_length=7, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_staff', models.CharField(choices=[('Sta', 'Staff'), ('Not', 'NotStaff')], default='Sta', help_text='Staff Status', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.TimeField(auto_now=True, null=True)),
                ('created_date', models.DateField(auto_now=True, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('receiver', models.CharField(max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachement')),
                ('status', models.CharField(blank=True, choices=[('Rec', 'Received'), ('Del', 'Delivered'), ('Red', 'Read')], help_text='Transaction Status', max_length=3, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.TimeField(auto_now=True, null=True)),
                ('created_date', models.DateField(auto_now=True, null=True)),
                ('action', models.TextField()),
                ('user_acting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_station', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
